version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bookio-server
    container_name: bookio-node-server
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  database:
    image: mongo:5.0.2
    container_name: bookio-mongo
    hostname: mongodbserver
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./docker-volumes/mongo:/data/db
    networks:
      - app-network

  redis:
    image: eqalpha/keydb:alpine
    container_name: bookio-redis-dev
    volumes:
      - ./docker-volumes/redis:/data
    restart: "always"
    networks:
      - app-network


networks:
  app-network:
    name: bookio-network
