version: '3.7'

services:
  server-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: shypple-server-dev
    container_name: shypple-node-server
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '9896:9896' # Debug port

    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app # Map all local files for hot-reload
      - /usr/src/app/node_modules/ # Exclude node_modules from volume
    command: 'yarn run dev:debug'
    networks:
      - app-network

  database-dev:
    image: mongo:5.0.2
    container_name: shypple-mongo-dev
    hostname: mongodbserver
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./docker-volumes/mongo:/data/db
    networks:
      - app-network
    ports:
      - '27020:27017'

  redis-dev:
    image: redis:6-alpine
    container_name: shypple-redis-dev
    volumes:
      - ./docker-volumes/redis:/data
    restart: "always"
    networks:
      - app-network

networks:
  app-network:
    name: shypple-network
